# Generated by Django 4.1.5 on 2023-04-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_facebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('post_count', models.IntegerField()),
            ],
        ),
    ]
