# Generated by Django 4.1.5 on 2023-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_facebook', '0002_createrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrequest',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
